#include <catch2/catch_test_macros.hpp>

#include <bio/translate.hh>

TEST_CASE("Translate sequence no surround", "[biolib][translate]")
{

    auto orfs = bio::translate(
            std::string{"GACTTTATATTTAGTGTTTGGAGCTTGATCTGCCATAGTAGGTACTGCTATAAGTGTGCTAATTCGGGTTGAATTAGGTCAACCTGGGAGATTATTAGGGGATGATCAATTATACAATGTAATTGTAACAGGACATGCTTTTGTAATGATTTTTTTTATAGTTATACCAATTTTAATTGGAGGTTTTGGAAATTGGTTAGTTCCTTTGATATTAGGAGCTCCCGATATAGCTTTTCCTCGGATAAATAATTTGAGATTTTGATTATTACCTCCTTCTTTATTATTATTATTTATTTCTTCTATAGAAGAAATAGGGGTTGGGGCAGGTTGGACTATTTACCCTCCTTTATCTTCTTTAGAAGGGCATAGAGGGAGCTCTGTAGATTTTGCTATTTTCTCTTTACATTTAGCAGGTGCTTCATCTATTATAGGGGCTATTAATTTTATTTCTACTATTTTTAATATACGTATATATGGTATAAGATTAGAAAAGGTTAGATTGTTTGTTTGGTCGGTTTTAATTACAGCTGTATTGTTATTATTATCATTACCAGTATTAGCAGGGGCTATTACTATATTATTAACCGATCGAAATTTTAATACTTCATTTTTTGATCCTGCTGGGGGAGGTGATCCTATTTTATTTCAACATTTATTT"},
            []([[maybe_unused]] std::size_t const index){
                return std::tuple{std::string{""}, std::string{""}};
            }
    );

    REQUIRE(orfs[0] == "DFIFSVWSLICHSRYCYKCANSG-IRSTWEIIRG-SIIQCNCNRTCFCNDFFYSYTNFNWRFWKLVSSFDIRSSRYSFSSDK-FEILIITSFFIIIIYFFYRRNRGWGRLDYLPSFIFFRRA-RELCRFCYFLFTFSRCFIYYRGY-FYFYYF-YTYIWYKIRKG-IVCLVGFNYSCIVIIIITSISRGYYYIINRSKF-YFIF-SCWGR-SYFISTFI");
    REQUIRE(orfs[1] == "TLYLVFGA-SAIVGTAISVLIRVELGQPGRLLGDDQLYNVIVTGHAFVMIFFIVIPILIGGFGNWLVPLILGAPDIAFPRINNLRF-LLPPSLLLLFISSIEEIGVGAGWTIYPPLSSLEGHRGSSVDFAIFSLHLAGASSIIGAINFISTIFNIRIYGIRLEKVRLFVWSVLITAVLLLLSLPVLAGAITILLTDRNFNTSFFDPAGGGDPILFQHLF");
    REQUIRE(orfs[2] == "LYI-CLELDLP--VLL-VC-FGLN-VNLGDY-GMINYTM-L-QDMLL--FFL-LYQF-LEVLEIG-FL-Y-ELPI-LFLG-II-DFDYYLLLYYYYLFLL-KK-GLGQVGLFTLLYLL-KGIEGAL-ILLFSLYI-QVLHLL-GLLILFLLFLIYVYMV-D-KRLDCLFGRF-LQLYCYYYHYQY-QGLLLYY-PIEILILHFLILLGEVILFYFNIY");
}

TEST_CASE("Translate sequence with surround", "[biolib][translate]")
{

    auto orfs = bio::translate(
            std::string{"AGCAGCAGAGAUGACGAGCAGAGCGAGCUGAAAGAAAAUGGAGCGCUGA"},
            [](std::size_t const index){
                return std::tuple{std::string{"b"} + std::to_string(index), std::to_string(index) + "e"};
            }
    );

    REQUIRE(orfs[0] == "SSRDDEQSELKENGAL");
    REQUIRE(orfs[1] == "AAEb0MTSRAS0e-KKb1MER1e-");
    REQUIRE(orfs[2] == "QQR-RAERAERKWSA");
}