#include <catch2/catch_test_macros.hpp>

#include <bio/translate.hh>

TEST_CASE("Translate sequence no surround", "[biolib][translate]")
{

    auto orfs = bio::translate(
        std::string{"GACTTTATATTTAGTGTTTGGAGCTTGATCTGCCATAGTAGGTACTGCTATAAGTGTGCTAATTCGGGTTGAATTAGGTCAACCTGGGAGATTATTAGGGGATGATCAATTATACAATGTAATTGTAACAGGACATGCTTTTGTAATGATTTTTTTTATAGTTATACCAATTTTAATTGGAGGTTTTGGAAATTGGTTAGTTCCTTTGATATTAGGAGCTCCCGATATAGCTTTTCCTCGGATAAATAATTTGAGATTTTGATTATTACCTCCTTCTTTATTATTATTATTTATTTCTTCTATAGAAGAAATAGGGGTTGGGGCAGGTTGGACTATTTACCCTCCTTTATCTTCTTTAGAAGGGCATAGAGGGAGCTCTGTAGATTTTGCTATTTTCTCTTTACATTTAGCAGGTGCTTCATCTATTATAGGGGCTATTAATTTTATTTCTACTATTTTTAATATACGTATATATGGTATAAGATTAGAAAAGGTTAGATTGTTTGTTTGGTCGGTTTTAATTACAGCTGTATTGTTATTATTATCATTACCAGTATTAGCAGGGGCTATTACTATATTATTAACCGATCGAAATTTTAATACTTCATTTTTTGATCCTGCTGGGGGAGGTGATCCTATTTTATTTCAACATTTATTT"}
    );

    REQUIRE(orfs[0].sequence == "DFIFSVWSLICHSRYCYKCANSG-IRSTWEIIRG-SIIQCNCNRTCFCNDFFYSYTNFNWRFWKLVSSFDIRSSRYSFSSDK-FEILIITSFFIIIIYFFYRRNRGWGRLDYLPSFIFFRRA-RELCRFCYFLFTFSRCFIYYRGY-FYFYYF-YTYIWYKIRKG-IVCLVGFNYSCIVIIIITSISRGYYYIINRSKF-YFIF-SCWGR-SYFISTFI");
    REQUIRE(orfs[1].sequence == "TLYLVFGA-SAIVGTAISVLIRVELGQPGRLLGDDQLYNVIVTGHAFVMIFFIVIPILIGGFGNWLVPLILGAPDIAFPRINNLRF-LLPPSLLLLFISSIEEIGVGAGWTIYPPLSSLEGHRGSSVDFAIFSLHLAGASSIIGAINFISTIFNIRIYGIRLEKVRLFVWSVLITAVLLLLSLPVLAGAITILLTDRNFNTSFFDPAGGGDPILFQHLF");
    REQUIRE(orfs[2].sequence == "LYI-CLELDLP--VLL-VC-FGLN-VNLGDY-GMINYTM-L-QDMLL--FFL-LYQF-LEVLEIG-FL-Y-ELPI-LFLG-II-DFDYYLLLYYYYLFLL-KK-GLGQVGLFTLLYLL-KGIEGAL-ILLFSLYI-QVLHLL-GLLILFLLFLIYVYMV-D-KRLDCLFGRF-LQLYCYYYHYQY-QGLLLYY-PIEILILHFLILLGEVILFYFNIY");
}

TEST_CASE("Translate sequence with surround", "[biolib][translate]")
{

    auto orfs = bio::translate(
        std::string{"AGCAGCAGAGAUGACGAGCAGAGCGAGCUGAAAGAAAAUGGAGCGCUGA"}
    );

    REQUIRE(orfs[0].sequence == "SSRDDEQSELKENGAL");
    REQUIRE(orfs[0].indices.empty());

    REQUIRE(orfs[1].sequence == "AAEMTSRAS-KKMER-");
    REQUIRE(orfs[1].indices.size() == 2);

    REQUIRE(orfs[1].indices[0].first == 3);
    REQUIRE(orfs[1].indices[0].second == 9);

    REQUIRE(orfs[1].indices[1].first == 12);
    REQUIRE(orfs[1].indices[1].second == 15);

    REQUIRE(orfs[2].sequence == "QQR-RAERAERKWSA");
    REQUIRE(orfs[2].indices.empty());
}
