export const data = [
  {
    name: "Alanine",
    abbreviation: "Ala",
    symbol: "A",
    molecularWeight: 89.1,
    molecularFormula: "C_{3}H_{7}NO_{2}",
    residueFormula: "C_{3}H_{5}NO",
    residueWeight: 71.08,
    pKa: 2.34,
    pKb: 9.69,
    pKx: null,
    pl: 6,
  },
  {
    name: "Arginine",
    abbreviation: "Arg",
    symbol: "R",
    molecularWeight: 174.2,
    molecularFormula: "C_{6}H_{14}N_{4}O_{2}",
    residueFormula: "C_{6}H_{12}N_{4}O",
    residueWeight: 156.19,
    pKa: 2.17,
    pKb: 9.04,
    pKx: 12.48,
    pl: 10.76,
  },
  {
    name: "Asparagine",
    abbreviation: "Asn",
    symbol: "N",
    molecularWeight: 132.12,
    molecularFormula: "C_{4}H_{8}N_{2}O_{3}",
    residueFormula: "C_{4}H_{6}N_{2}O_{2}",
    residueWeight: 114.11,
    pKa: 2.02,
    pKb: 8.8,
    pKx: null,
    pl: 5.41,
  },
  {
    name: "Aspartic acid",
    abbreviation: "Asp",
    symbol: "D",
    molecularWeight: 133.11,
    molecularFormula: "C_{4}H_{7}NO_{4}",
    residueFormula: "C_{4}H_{5}NO_{3}",
    residueWeight: 115.09,
    pKa: 1.88,
    pKb: 9.6,
    pKx: 3.65,
    pl: 2.77,
  },
  {
    name: "Cysteine",
    abbreviation: "Cys",
    symbol: "C",
    molecularWeight: 121.16,
    molecularFormula: "C_{3}H_{7}NO_{2}S",
    residueFormula: "C_{3}H_{5}NOS",
    residueWeight: 103.15,
    pKa: 1.96,
    pKb: 10.28,
    pKx: 8.18,
    pl: 5.07,
  },
  {
    name: "Glutamic acid",
    abbreviation: "Glu",
    symbol: "E",
    molecularWeight: 147.13,
    molecularFormula: "C_{5}H_{9}NO_{4}",
    residueFormula: "C_{5}H_{7}NO_{3}",
    residueWeight: 129.12,
    pKa: 2.19,
    pKb: 9.67,
    pKx: 4.25,
    pl: 3.22,
  },
  {
    name: "Glutamine",
    abbreviation: "Gln",
    symbol: "Q",
    molecularWeight: 146.15,
    molecularFormula: "C_{5}H_{10}N_{2}O_{3}",
    residueFormula: "C_{5}H_{8}N_{2}O_{2}",
    residueWeight: 128.13,
    pKa: 2.17,
    pKb: 9.13,
    pKx: null,
    pl: 5.65,
  },
  {
    name: "Glycine",
    abbreviation: "Gly",
    symbol: "G",
    molecularWeight: 75.07,
    molecularFormula: "C_{2}H_{5}NO_{2}",
    residueFormula: "C_{2}H_{3}NO",
    residueWeight: 57.05,
    pKa: 2.34,
    pKb: 9.6,
    pKx: null,
    pl: 5.97,
  },
  {
    name: "Histidine",
    abbreviation: "His",
    symbol: "H",
    molecularWeight: 155.16,
    molecularFormula: "C_{6}H_{9}N_{3}O_{2}",
    residueFormula: "C_{6}H_{7}N_{3}O",
    residueWeight: 137.14,
    pKa: 1.82,
    pKb: 9.17,
    pKx: 6,
    pl: 7.59,
  },
  {
    name: "Hydroxyproline",
    abbreviation: "Hyp",
    symbol: "O",
    molecularWeight: 131.13,
    molecularFormula: "C_{5}H_{9}NO_{3}",
    residueFormula: "C_{5}H_{7}NO_{2}",
    residueWeight: 113.11,
    pKa: 1.82,
    pKb: 9.65,
    pKx: null,
    pl: null,
  },
  {
    name: "Isoleucine",
    abbreviation: "Ile",
    symbol: "I",
    molecularWeight: 131.18,
    molecularFormula: "C_{6}H_{13}NO_{2}",
    residueFormula: "C_{6}H_{11}NO",
    residueWeight: 113.16,
    pKa: 2.36,
    pKb: 9.6,
    pKx: null,
    pl: 6.02,
  },
  {
    name: "Leucine",
    abbreviation: "Leu",
    symbol: "L",
    molecularWeight: 131.18,
    molecularFormula: "C_{6}H_{13}NO_{2}",
    residueFormula: "C_{6}H_{11}NO",
    residueWeight: 113.16,
    pKa: 2.36,
    pKb: 9.6,
    pKx: null,
    pl: 5.98,
  },
  {
    name: "Lysine",
    abbreviation: "Lys\n",
    symbol: "K",
    molecularWeight: 146.19,
    molecularFormula: "C_{6}H_{14}N_{2}O_{2}",
    residueFormula: "C_{6}H_{12}N_{2}O",
    residueWeight: 128.18,
    pKa: 2.18,
    pKb: 8.95,
    pKx: 10.53,
    pl: 9.74,
  },
  {
    name: "Methionine",
    abbreviation: "Met",
    symbol: "M",
    molecularWeight: 149.21,
    molecularFormula: "C_{5}H_{11}NO_{2}S",
    residueFormula: "C_{5}H_{9}NOS",
    residueWeight: 131.2,
    pKa: 2.28,
    pKb: 9.21,
    pKx: null,
    pl: 5.74,
  },
  {
    name: "Phenylalanine",
    abbreviation: "Phe",
    symbol: "F",
    molecularWeight: 165.19,
    molecularFormula: "C_{9}H_{11}NO_{2}",
    residueFormula: "C_{9}H_{9}NO",
    residueWeight: 147.18,
    pKa: 1.83,
    pKb: 9.13,
    pKx: null,
    pl: 5.48,
  },
  {
    name: "Proline",
    abbreviation: "Pro",
    symbol: "P",
    molecularWeight: 115.13,
    molecularFormula: "C_{5}H_{9}NO_{2}",
    residueFormula: "C_{5}H_{7}NO",
    residueWeight: 97.12,
    pKa: 1.99,
    pKb: 10.6,
    pKx: null,
    pl: 6.3,
  },
  {
    name: "Pyroglutamatic",
    abbreviation: "Glp",
    symbol: "U",
    molecularWeight: 139.11,
    molecularFormula: "C_{5}H_{7}NO_{3}",
    residueFormula: "C_{5}H_{5}NO_{2}",
    residueWeight: 121.09,
    pKa: null,
    pKb: null,
    pKx: null,
    pl: 5.68,
  },
  {
    name: "Serine",
    abbreviation: "Ser",
    symbol: "S",
    molecularWeight: 105.09,
    molecularFormula: "C_{3}H_{7}NO_{3}",
    residueFormula: "C_{3}H_{5}NO_{2}",
    residueWeight: 87.08,
    pKa: 2.21,
    pKb: 9.15,
    pKx: null,
    pl: 5.68,
  },
  {
    name: "Threonine",
    abbreviation: "Thr",
    symbol: "T",
    molecularWeight: 119.12,
    molecularFormula: "C_{4}H_{9}NO_{3}",
    residueFormula: "C_{4}H_{7}NO_{2}",
    residueWeight: 101.11,
    pKa: 2.09,
    pKb: 9.1,
    pKx: null,
    pl: 5.6,
  },
  {
    name: "Tryptophan",
    abbreviation: "Trp",
    symbol: "W",
    molecularWeight: 204.23,
    molecularFormula: "C_{11}H_{12}N_{2}O_{2}",
    residueFormula: "C_{11}H_{10}N_{2}O",
    residueWeight: 186.22,
    pKa: 2.83,
    pKb: 9.39,
    pKx: null,
    pl: 5.89,
  },
  {
    name: "Tyrosine",
    abbreviation: "Tyr",
    symbol: "Y",
    molecularWeight: 181.19,
    molecularFormula: "C_{9}H_{11}NO_{3}",
    residueFormula: "C_{9}H_{9}NO_{2}",
    residueWeight: 163.18,
    pKa: 2.2,
    pKb: 9.11,
    pKx: 10.07,
    pl: 5.66,
  },
  {
    name: "Valine",
    abbreviation: "Val",
    symbol: "V",
    molecularWeight: 117.15,
    molecularFormula: "C_{5}H_{11}NO_{2}",
    residueFormula: "C_{5}H_{9}NO",
    residueWeight: 99.13,
    pKa: 2.32,
    pKb: 9.62,
    pKx: null,
    pl: 5.96,
  },
] as AminoAcidData[];

export type AminoAcidData = {
  name: string;
  abbreviation: string;
  symbol: string;
  molecularWeight: number;
  residueWeight: number;
  molecularFormula: string;
  residueFormula: string;
  pKa: number;
  pKb: number;
  pKx: number;
  pl: number;
};
