name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Cpp Linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          style: ''
          tidy-checks: ''
          database: ${{github.workspace}}/build
          version: '14'

      - name: Check cpp linter output
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
