name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      CCACHE_SLOPPINESS: 'pch_defines,time_macros'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHECKOUT_PAT }}
          submodules: true
          fetch-depth: 0

      - name: Setup cache lto
        uses: actions/cache@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          path: 'emsdk-cache'
          key:  'emsdk-cache-lto'

      - name: Setup cache no lto
        uses: actions/cache@v3
        if: ${{ github.ref != 'refs/heads/master' }}
        with:
          path: 'emsdk-cache'
          key:  'emsdk-cache'

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.27
          actions-cache-folder: 'emsdk-cache'

      - name: Setup conan
        uses: turtlebrowser/get-conan@main

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}

      - name: Configure CMake
        run: emcmake cmake -B ${{ github.workspace }}/build-emsdk -S ${{ github.workspace }} -DCMAKE_BUILD_TYPE:STRING="Release" -DCMAKE_C_COMPILER_LAUNCHER:STRING="ccache" -DCMAKE_CXX_COMPILER_LAUNCHER:STRING="ccache" -DDOXYGEN_ENABLED:BOOL=OFF -DTESTS_ENABLED:BOOL=OFF -DLTO_ENABLED:BOOL=${{ github.ref == 'refs/heads/master' && 'ON' || 'OFF' }} -DEMSCRIPTEN_EVAL_CTORS:BOOL=${{ github.ref == 'refs/heads/master' && 'ON' || 'OFF' }}

      - name: Build wasm
        run: cmake --build ${{ github.workspace }}/build-emsdk --parallel $(($(nproc)+1))

      - name: Install yarn
        uses: bahmutov/npm-install@v1
        with:
          working-directory: web

      - name: Build web
        working-directory: ./web
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/web/dist