name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CHECKOUT_PAT }}
          submodules: true
          fetch-depth: 0

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: 'emsdk-cache'
          key:  'emsdk-cache'

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.27
          actions-cache-folder: 'emsdk-cache'

      - name: Setup conan
        uses: turtlebrowser/get-conan@main

      - name: Configure CMake
        run: emcmake cmake -B ${{ github.workspace }}/build-emsdk -S ${{ github.workspace }} -DCMAKE_BUILD_TYPE:STRING="Release" -DDOXYGEN_ENABLED:BOOL=OFF -DTESTS_ENABLED:BOOL=OFF

      - name: Build wasm
        run: cmake --build ${{ github.workspace }}/build-emsdk

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/web/dist